In [1]:
from tensorflow.keras.preprocessing.text import one_hot

C:\Users\praka\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

# One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4979, 5362, 1310, 6581], [4979, 5362, 1310, 3972], [4979, 35, 1310, 9409], [3139, 3774, 4032, 6743, 667], [3139, 3774, 4032, 6743, 1632], [8138, 4979, 1554, 1310, 7679], [3505, 8621, 2218, 6743]]


# Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4979 5362 1310 6581]
 [   0    0    0    0 4979 5362 1310 3972]
 [   0    0    0    0 4979   35 1310 9409]
 [   0    0    0 3139 3774 4032 6743  667]
 [   0    0    0 3139 3774 4032 6743 1632]
 [   0    0    0 8138 4979 1554 1310 7679]
 [   0    0    0    0 3505 8621 2218 6743]]


In [13]:
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 158ms/step
[[[ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902
    0.02333447 -0.02214972  0.0246261   0.01013038  0.00848398]
  [ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902
    0.02333447 -0.02214972  0.0246261   0.01013038  0.00848398]
  [ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902
    0.02333447 -0.02214972  0.0246261   0.01013038  0.00848398]
  [ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902
    0.02333447 -0.02214972  0.0246261   0.01013038  0.00848398]
  [ 0.03695431 -0.03819506  0.01526449  0.01324109  0.03056881
   -0.04539379 -0.01602016 -0.00752057  0.04741842  0.02239753]
  [ 0.03278421  0.00460615  0.0095103   0.04448948  0.02840245
    0.01532483 -0.03966223 -0.01593704 -0.04776762  0.04947202]
  [-0.0007337   0.00954024 -0.00203979  0.048953   -0.0270471
    0.04636673 -0.02591262 -0.0306948  -0.045824   -0.00146832]
  [ 0.00825938  0.01406113 -0.02067226 -0.03020136 -0.01052

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 4979, 5362, 1310, 6581])

In [19]:
print(model.predict(embedded_docs)[2])

1/1 [==============================] - 0s 18ms/step
[[ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902  0.02333447
  -0.02214972  0.0246261   0.01013038  0.00848398]
 [ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902  0.02333447
  -0.02214972  0.0246261   0.01013038  0.00848398]
 [ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902  0.02333447
  -0.02214972  0.0246261   0.01013038  0.00848398]
 [ 0.00796809 -0.03730279  0.0460296   0.01392119  0.03323902  0.02333447
  -0.02214972  0.0246261   0.01013038  0.00848398]
 [ 0.03695431 -0.03819506  0.01526449  0.01324109  0.03056881 -0.04539379
  -0.01602016 -0.00752057  0.04741842  0.02239753]
 [-0.04983709  0.04343933 -0.03334709 -0.00098955  0.04555945  0.00510154
   0.03806065 -0.01897702 -0.04099928  0.01883257]
 [-0.0007337   0.00954024 -0.00203979  0.048953   -0.0270471   0.04636673
  -0.02591262 -0.0306948  -0.045824   -0.00146832]
 [-0.04268533 -0.0096102  -0.04003907  0.02564779 -0.02420547 -0.04869799